/* Given two strings x and y, write a function 
that returns how many times x can be repeated to generate y. 
If y cannot be generated by repeating x, return -1.

Example:
repeat('pi', 'pipipipi')
> 4
repeat('danger', 'cassidy')
> -1
  */
  repeat=(str,strin) =>{
   var a=strin.split(str)
   var unique= [...new Set(a)]
  
       if(unique == '' ){
           return a.length-1
       }else{
           return -1
       }
  }
  console.log(repeat('pi', 'pipipipi'));
  console.log(repeat('danger', 'cassidy'));